[filenames, path] = uigetfile('*.csv', 'Select CSV files', 'MultiSelect', 'on');
if isequal(filenames, 0)
    % User clicked Cancel
    return;
end
% If only one file was selected, convert it to a cell array
if ~iscell(filenames)
    filenames = {filenames};
end

for i = 1:length(filenames)
    filename = filenames{i};
    [~, name, ~] = fileparts(filename);
    data = readmatrix(fullfile(path, filename));
    data = data(5:end, :);
    data = data(:,2);
fs = 10000;
% Set the fs based on the filename
% Search for the pattern "(\d+)fs" in the filename
match = regexp(filename, '(\d+)fs', 'match');

% If a match is found, extract the digits and convert to a double
if ~isempty(match)
    fs_str = match{1}(1:end-2); % Remove the "fs" suffix
    fs = str2double(fs_str);
end

%Compute scalogram

% Generated by MATLAB(R) 9.12 and Wavelet Toolbox 6.1.
% Generated on: 13-4月-2023 07:50:45


%Compute time vector
t = 0:1/fs:(length(data)*1/fs)-1/fs;

%Compute CWT
%If necessary, substitute workspace variable name for USTC_SPRING as first input to cwt() function in code below
%Run the function call below without output arguments to plot the results
[waveletTransform,frequency] = cwt(data, fs);
scalogram = abs(waveletTransform);

%Draw scalogram
figure;
imagesc(t, log10(frequency), log(scalogram));
% ylim([0 100]);
set(gca,'YDir','normal');
xlabel('Time (s)');
ylabel('Frequency (Hz)');
title('Scalogram');
colorbar;

end